#!/bin/bash
# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# background
# border
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=SCRIPT_DIR/$BLOCK_NAME
separator_block_width=15
markup=none

[hello]
full_text=Hello World
instance=once

# Volume indicator
#
# The first parameter sets the step (and units to display)
# The second parameter overrides the mixer selection
# See the script for details.
[volume]
command=SCRIPT_DIR/volume
#label=VOL
label=♪
instance=Master
#instance=PCM
interval=once
signal=10

# Memory usage
#
# The type defaults to "mem" if the instance is not specified.
[memory]
label=MEM
separator=false
interval=30

[wifi]
#instance=wlp3s0
interval=10
separator=false

[load_average]
interval=10

# Date Time
#
[time]
command=date '+%Y-%m-%d %H:%M:%S'
interval=5
